roles_user = {
    "Administrateur": "ADMIN", # Admin (all rights : can create, edit, delete, read and manage users)
    "Éditeur": "EDITOR", # Editor (can create, edit and delete, validate except manage users)
    "Lecteur": "READER" # Reader (can read only)
}

type_patent_relations = {
    "Associé": "PARTNER",
    "Parrain": "SPONSOR",
    "Successeur": "SUCCESSOR",
    "Prédécesseur": "PREDECESSOR"
}

countries_ISO_3166 = {
    "Afghanistan": "AF",
    "Afrique du Sud": "ZA",
    "Åland, Îles": "AX",
    "Albanie": "AL",
    "Algérie": "DZ",
    "Allemagne": "DE",
    "Allemagne de l'EST": "DD",
    "Andorre": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctique": "AQ",
    "Antigua et Barbuda": "AG",
    "Antilles néerlandaises": "AN",
    "Arabie Saoudite": "SA",
    "Argentine": "AR",
    "Arménie": "AM",
    "Aruba": "AW",
    "Australie": "AU",
    "Autriche": "AT",
    "Azerbaïdjan": "AZ",
    "Bahamas": "BS",
    "Bahrein": "BH",
    "Bangladesh": "BD",
    "Barbade": "BB",
    "Bélarus": "BY",
    "Belgique": "BE",
    "Bélize": "BZ",
    "Bénin": "BJ",
    "Bermudes": "BM",
    "Bhoutan": "BT",
    "Bolivie (État plurinational de)": "BO",
    "Bonaire, Saint-Eustache et Saba": "BQ",
    "Bosnie-Herzégovine": "BA",
    "Botswana": "BW",
    "Bouvet, Ile": "BV",
    "Brésil": "BR",
    "Brunéi Darussalam": "BN",
    "Bulgarie": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cabo Verde": "CV",
    "Caïmans, Iles": "KY",
    "Cambodge": "KH",
    "Cameroun": "CM",
    "Canada": "CA",
    "Chili": "CL",
    "Chine": "CN",
    "Christmas, île": "CX",
    "Chypre": "CY",
    "Cocos/Keeling (Îles)": "CC",
    "Colombie": "CO",
    "Comores": "KM",
    "Congo": "CG",
    "Congo, République démocratique du": "CD",
    "Cook, Iles": "CK",
    "Corée, République de": "KR",
    "Corée, République populaire démocratique de": "KP",
    "Costa Rica": "CR",
    "Côte d'Ivoire": "CI",
    "Croatie": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Danemark": "DK",
    "Djibouti": "DJ",
    "Dominicaine, République": "DO",
    "Dominique": "DM",
    "Egypte": "EG",
    "El Salvador": "SV",
    "Emirats arabes unis": "AE",
    "Equateur": "EC",
    "Erythrée": "ER",
    "Espagne": "ES",
    "Estonie": "EE",
    "Etats-Unis d'Amérique": "US",
    "Ethiopie": "ET",
    "Falkland/Malouines (Îles)": "FK",
    "Féroé, îles": "FO",
    "Fidji": "FJ",
    "Finlande": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambie": "GM",
    "Géorgie": "GE",
    "Géorgie du sud et les îles Sandwich du sud": "GS",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Grèce": "GR",
    "Grenade": "GD",
    "Groenland": "GL",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernesey": "GG",
    "Guinée": "GN",
    "Guinée-Bissau": "GW",
    "Guinée équatoriale": "GQ",
    "Guyana": "GY",
    "Guyane française": "GF",
    "Haïti": "HT",
    "Heard, Ile et MacDonald, îles": "HM",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hongrie": "HU",
    "Île de Man": "IM",
    "Îles mineures éloignées des Etats-Unis": "UM",
    "Îles vierges britanniques": "VG",
    "Îles vierges des Etats-Unis": "VI",
    "Inde": "IN",
    "Indien (Territoire britannique de l'océan)": "IO",
    "Indonésie": "ID",
    "Iran, République islamique d'": "IR",
    "Iraq": "IQ",
    "Irlande": "IE",
    "Islande": "IS",
    "Israël": "IL",
    "Italie": "IT",
    "Jamaïque": "JM",
    "Japon": "JP",
    "Jersey": "JE",
    "Jordanie": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kirghizistan": "KG",
    "Kiribati": "KI",
    "Koweït": "KW",
    "Lao, République démocratique populaire": "LA",
    "Lesotho": "LS",
    "Lettonie": "LV",
    "Liban": "LB",
    "Libéria": "LR",
    "Libye": "LY",
    "Liechtenstein": "LI",
    "Lituanie": "LT",
    "Luxembourg": "LU",
    "Macao": "MO",
    "Macédoine, l'ex-République yougoslave de": "MK",
    "Madagascar": "MG",
    "Malaisie": "MY",
    "Malawi": "MW",
    "Maldives": "MV",
    "Mali": "ML",
    "Malte": "MT",
    "Mariannes du nord, Iles": "MP",
    "Maroc": "MA",
    "Marshall, Iles": "MH",
    "Martinique": "MQ",
    "Maurice": "MU",
    "Mauritanie": "MR",
    "Mayotte": "YT",
    "Mexique": "MX",
    "Micronésie, Etats Fédérés de": "FM",
    "Moldova, République de": "MD",
    "Monaco": "MC",
    "Mongolie": "MN",
    "Monténégro": "ME",
    "Montserrat": "MS",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibie": "NA",
    "Nauru": "NR",
    "Népal": "NP",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigéria": "NG",
    "Niue": "NU",
    "Norfolk, Ile": "NF",
    "Norvège": "NO",
    "Nouvelle-Calédonie": "NC",
    "Nouvelle-Zélande": "NZ",
    "Oman": "OM",
    "Ouganda": "UG",
    "Ouzbékistan": "UZ",
    "Pakistan": "PK",
    "Palaos": "PW",
    "Palestine, Etat de": "PS",
    "Panama": "PA",
    "Papouasie-Nouvelle-Guinée": "PG",
    "Paraguay": "PY",
    "Pays-Bas": "NL",
    "Pays inconnu": "XX",
    "Pays multiples": "ZZ",
    "Pérou": "PE",
    "Philippines": "PH",
    "Pitcairn": "PN",
    "Pologne": "PL",
    "Polynésie française": "PF",
    "Porto Rico": "PR",
    "Portugal": "PT",
    "Qatar": "QA",
    "République arabe syrienne": "SY",
    "République centrafricaine": "CF",
    "Réunion": "RE",
    "Roumanie": "RO",
    "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord": "GB",
    "Russie, Fédération de": "RU",
    "Rwanda": "RW",
    "Sahara occidental": "EH",
    "Saint-Barthélemy": "BL",
    "Saint-Kitts-et-Nevis": "KN",
    "Saint-Marin": "SM",
    "Saint-Martin (partie française)": "MF",
    "Saint-Martin (partie néerlandaise)": "SX",
    "Saint-Pierre-et-Miquelon": "PM",
    "Saint-Siège": "VA",
    "Saint-Vincent-et-les-Grenadines": "VC",
    "Sainte-Hélène, Ascension et Tristan da Cunha": "SH",
    "Sainte-Lucie": "LC",
    "Salomon, Iles": "SB",
    "Samoa": "WS",
    "Samoa américaines": "AS",
    "Sao Tomé-et-Principe": "ST",
    "Sénégal": "SN",
    "Serbie": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapour": "SG",
    "Slovaquie": "SK",
    "Slovénie": "SI",
    "Somalie": "SO",
    "Soudan": "SD",
    "Soudan du Sud": "SS",
    "Sri Lanka": "LK",
    "Suède": "SE",
    "Suisse": "CH",
    "Suriname": "SR",
    "Svalbard et île Jan Mayen": "SJ",
    "Swaziland": "SZ",
    "Tadjikistan": "TJ",
    "Taïwan, Province de Chine": "TW",
    "Tanzanie, République unie de": "TZ",
    "Tchad": "TD",
    "Tchécoslovaquie": "CS",
    "Tchèque, République": "CZ",
    "Terres australes françaises": "TF",
    "Thaïlande": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinité-et-Tobago": "TT",
    "Tunisie": "TN",
    "Turkménistan": "TM",
    "Turks-et-Caïcos (Îles)": "TC",
    "Turquie": "TR",
    "Tuvalu": "TV",
    "Ukraine": "UA",
    "URSS": "SU",
    "Uruguay": "UY",
    "Vanuatu": "VU",
    "Vatican": "VA",
    "Venezuela (République bolivarienne du)": "VE",
    "Viet Nam": "VN",
    "Viet Nam (Sud)": "VD",
    "Wallis et Futuna": "WF",
    "Yémen": "YE",
    "Yougoslavie": "YU",
    "Zaïre": "ZR",
    "Zambie": "ZM",
    "Zimbabwe": "ZW"
}

departments_INSEE_code = {
    'Default': 'DEP_00',
    'Ain': 'DEP_01',
    'Aisne': 'DEP_02',
    'Allier': 'DEP_03',
    'Alpes-de-Haute-Provence': 'DEP_04',
    'Hautes-Alpes': 'DEP_05',
    'Alpes-Maritimes': 'DEP_06',
    'Ardèche': 'DEP_07',
    'Ardennes': 'DEP_08',
    'Ariège': 'DEP_09',
    'Aube': 'DEP_10',
    'Aude': 'DEP_11',
    'Aveyron': 'DEP_12',
    'Bouches-du-Rhône': 'DEP_13',
    'Calvados': 'DEP_14',
    'Cantal': 'DEP_15',
    'Charente': 'DEP_16',
    'Charente-Maritime': 'DEP_17',
    'Cher': 'DEP_18',
    'Corrèze': 'DEP_19',
    "Côte-d'Or": 'DEP_21',
    "Côtes-d'Armor": 'DEP_22',
    'Creuse': 'DEP_23',
    'Dordogne': 'DEP_24',
    'Doubs': 'DEP_25',
    'Drôme': 'DEP_26',
    'Eure': 'DEP_27',
    'Eure-et-Loir': 'DEP_28',
    'Finistère': 'DEP_29',
    'Corse-du-Sud': 'DEP_2A',
    'Haute-Corse': 'DEP_2B',
    'Gard': 'DEP_30',
    'Haute-Garonne': 'DEP_31',
    'Gers': 'DEP_32',
    'Gironde': 'DEP_33',
    'Hérault': 'DEP_34',
    'Ille-et-Vilaine': 'DEP_35',
    'Indre': 'DEP_36',
    'Indre-et-Loire': 'DEP_37',
    'Isère': 'DEP_38',
    'Jura': 'DEP_39',
    'Landes': 'DEP_40',
    'Loir-et-Cher': 'DEP_41',
    'Loire': 'DEP_42',
    'Haute-Loire': 'DEP_43',
    'Loire-Atlantique': 'DEP_44',
    'Loiret': 'DEP_45',
    'Lot': 'DEP_46',
    'Lot-et-Garonne': 'DEP_47',
    'Lozère': 'DEP_48',
    'Maine-et-Loire': 'DEP_49',
    'Manche': 'DEP_50',
    'Marne': 'DEP_51',
    'Haute-Marne': 'DEP_52',
    'Mayenne': 'DEP_53',
    'Meurthe-et-Moselle': 'DEP_54',
    'Meuse': 'DEP_55',
    'Morbihan': 'DEP_56',
    'Moselle': 'DEP_57',
    'Nièvre': 'DEP_58',
    'Nord': 'DEP_59',
    'Oise': 'DEP_60',
    'Orne': 'DEP_61',
    'Pas-de-Calais': 'DEP_62',
    'Puy-de-Dôme': 'DEP_63',
    'Pyrénées-Atlantiques': 'DEP_64',
    'Hautes-Pyrénées': 'DEP_65',
    'Pyrénées-Orientales': 'DEP_66',
    'Bas-Rhin': 'DEP_67',
    'Haut-Rhin': 'DEP_68',
    'Rhône': 'DEP_69',
    'Haute-Saône': 'DEP_70',
    'Saône-et-Loire': 'DEP_71',
    'Sarthe': 'DEP_72',
    'Savoie': 'DEP_73',
    'Haute-Savoie': 'DEP_74',
    'Paris': 'DEP_75',
    'Seine-Maritime': 'DEP_76',
    'Seine-et-Marne': 'DEP_77',
    'Yvelines': 'DEP_78',
    'Deux-Sèvres': 'DEP_79',
    'Somme': 'DEP_80',
    'Tarn': 'DEP_81',
    'Tarn-et-Garonne': 'DEP_82',
    'Var': 'DEP_83',
    'Vaucluse': 'DEP_84',
    'Vendée': 'DEP_85',
    'Vienne': 'DEP_86',
    'Haute-Vienne': 'DEP_87',
    'Vosges': 'DEP_88',
    'Yonne': 'DEP_89',
    'Territoire de Belfort': 'DEP_90',
    'Essonne': 'DEP_91',
    'Hauts-de-Seine': 'DEP_92',
    'Seine-Saint-Denis': 'DEP_93',
    'Val-de-Marne': 'DEP_94',
    "Val-d'Oise": 'DEP_95',
    'Guadeloupe': 'DEP_971',
    'Martinique': 'DEP_972',
    'Guyane': 'DEP_973',
    'La Réunion': 'DEP_974',
    'Mayotte': 'DEP_976'
}
