"""
def test_fill_form_and_create_person(flask_server, page):
    # Accède à la page contenant le formulaire
    page.goto("http://127.0.0.1:8888/dil/admin/person/")
    page.get_by_role("link", name=" Imprimeurs").click()
    page.get_by_role("link", name="Créer").click()
    page.get_by_role("textbox", name="Nom  *").click()
    page.get_by_role("textbox", name="Nom  *").fill("deeffef")
    page.get_by_role("list").filter(has_text="Prénom(s)").click()
    page.get_by_role("textbox", name="Prénom(s)").fill("efefefef")
    page.locator("#select2-drop-mask").click()
    page.get_by_role("textbox", name="Date de naissance ").click()
    page.get_by_role("textbox", name="Date de naissance ").fill("effeffef")
    page.get_by_role("list").filter(has_text="Prénom(s)").click()
    page.get_by_role("textbox", name="Prénom(s)").fill("effefe,")
    page.get_by_role("textbox", name="Ville de naissance ").click()
    page.get_by_role("textbox", name="Ville de naissance ").click()
    page.get_by_role("textbox", name="Ville de naissance ").fill("fe")
    page.get_by_role("link", name="Indiquer la ville de").click()
    page.get_by_role("combobox", name="Ville de naissance (réfé").fill("f")
    page.get_by_role("option", name="< Ville : 107 | Confort (").click()
    page.locator("#quill-editor-professional_information").get_by_role("paragraph").click()
    page.locator("#quill-editor-professional_information div").first.fill("fefefeff\n\n\n\n\nfefefe")
    page.get_by_role("button", name="Enregistrer", exact=True).click()
    page.get_by_role("textbox", name="Date de naissance ").click()
    page.get_by_role("textbox", name="Date de naissance ").fill("1415")
    page.get_by_role("button", name="Enregistrer", exact=True).click()
"""